secondExercise/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('webshop.urls')),
    path('webshop/', include('webshop.urls')),
    path('admin/', admin.site.urls),

]

webshop/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^search/$', views.search, name="search"),
    url(r'^accounts/login/$', views.custom_login, name='login'),
    url(r'^login/$', views.custom_login, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('cart/', views.cart, name='cart'),
    path('cart/buy/', views.buy_cart, name='buy_cart_base'),
    path('cart/buy/<str:email>/', views.buy_cart, name='buy_cart'),
    path('add/<int:item_pk>/', views.add_item_to_cart, name='add_item_to_cart'),
    path('update/', views.update_item_in_cart, name='update_item_in_cart_base'),
    path('update/<int:item_pk>/<int:amount>/', views.update_item_in_cart, name='update_item_in_cart'),
    path('remove/<int:item_pk>/', views.remove_item_from_cart, name='remove_in_cart'),
    path('delete/<int:item_pk>/', views.delete_item_from_cart, name='delete_item_from_cart')
]

webshop/models.py
import math

from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models

from secondExercise.helper_functions import OutOfStockError


# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name_plural = "Brands"
        db_table = "brands"


class Tag(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name_plural = "Tags"
        db_table = "tags"


class Item(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    brand = models.ForeignKey("Brand", on_delete=models.CASCADE, default=1)
    tag = models.ManyToManyField("Tag")
    stock = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def get_item_percentage_price(self):
        try:
            discount = DiscountPercentage.objects.get(item=self)
            return round(self.price * (1 - discount.percentage), 2)
        except ObjectDoesNotExist:
            return False

    # Returns the type of discount and how much it is
    def get_discount(self):
        try:
            # Percentage discount
            discount = DiscountPercentage.objects.get(item=self)
            return  ("{:2.0f}% off").format(discount.percentage * 100)
        except ObjectDoesNotExist:
            # Package discount
            try:
                discount = DiscountPackage.objects.get(item=self)
                return ("{} for {}").format(discount.buyx, discount.fory)
            except ObjectDoesNotExist:
                return False

    class Meta():
        verbose_name_plural = "Items"
        db_table = "items"


class DiscountPercentage(models.Model):
    item = models.ForeignKey("Item", on_delete=models.CASCADE, related_name='discount')
    percentage = models.DecimalField(max_digits=3, decimal_places=2)

    class Meta():
        db_table = "discount_percentages"


class DiscountPackage(models.Model):
    item = models.ForeignKey("Item", on_delete=models.CASCADE)
    buyx = models.IntegerField()
    fory = models.IntegerField()

    class Meta():
        db_table = "discount_packages"

    def get_new_amount(self, quantity):
        return (math.floor(quantity / self.buyx) * self.fory) + (quantity % self.buyx)


class Cart(models.Model):
    items = models.ManyToManyField('Order')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return '%s' % self.owner

    def add_item(self, item):
        try:
            order = self.items.get(item=item)
            order.add_quantity(1)
        except ObjectDoesNotExist:
            self.items.add(Order.objects.create(item=item))
            self.save()

    def update_item(self, item, amount):
        try:
            order = self.items.get(item=item)
            if amount >= 1:
                order.update_quantity(amount)
            elif amount <= 0:
                self.delete_item(item)
            self.save()
        except ObjectDoesNotExist:
            self.items.add(Order.objects.create(item=item))
            self.save()

    def remove_item(self, item):
        try:
            order = self.items.get(item=item)
            order.quantity -= 1
            if order.quantity <= 0:
                self.delete_item(item)
                return
            order.save()
        except ObjectDoesNotExist:
            pass

    def delete_item(self, item):
        try:
            self.items.remove(self.items.get(item=item))
            self.save()
        except ObjectDoesNotExist:
            pass

    def update_stock(self):
        for order in self.items.all():
            order.item.stock -= order.quantity
            order.item.save()

    def get_total(self):
        total = 0
        for order in self.items.all()[:]:
            total += order.get_order_total()
        return total


class Order(models.Model):
    item = models.ForeignKey('Item', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    # Increases quantity by amount if in stock.
    def add_quantity(self, amount):
        if self.item.stock < (self.quantity + amount):
            raise OutOfStockError()
        self.quantity += amount
        self.save()

    # Sets quantity by amount if in stock, or deletes order.
    def update_quantity(self, quantity):
        if self.item.stock < quantity:
            raise OutOfStockError()
        self.quantity = quantity
        self.save()


    # Calculates the order total
    def get_order_total(self):
        try:
            # Percentage discount
            # DiscountPercentage gives the percentile reduction
            # So we subtract it from 1
            discount = DiscountPercentage.objects.get(item=self.item)
            return round(self.item.price * (1 - discount.percentage) * self.quantity, 2)
        except ObjectDoesNotExist:
            try:
                #Package discount
                discount = DiscountPackage.objects.get(item=self.item)
                discount_total = self.item.price * int(self.quantity / discount.buyx) * discount.fory
                rest_total = self.item.price * (self.quantity % discount.buyx)
                return discount_total + rest_total
            except ObjectDoesNotExist:
                # No discount
                return round(self.item.price * self.quantity, 2)

webshop/views.py
import django_filters
from django import forms
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import login
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render

from secondExercise.helper_functions import OutOfStockError, send_confirmation_email
from .models import Item, Brand, Tag, Cart


@login_required
def index(request):
	item_list = ItemsFilter(request.GET, queryset=Item.objects.filter(stock__gt=0)[:5])
	context = {
		'item_list': item_list,
	}
	return render(request, "index.html", context)


def detail(request, item_id):
	item = get_object_or_404(Item, pk=item_id)
	context = {
		'item': item,
	}
	return render(request, 'detail.html', context)


def custom_login(request):
	if request.user.is_authenticated:
		return redirect('index')
	else:
		return login(request)


def signup(request):
	if request.user.is_authenticated:
		return redirect('index')

	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('index')
	else:
		form = UserCreationForm()
	return render(request, 'signup.html', {'form': form})


def search(request):
	itemsFilter = ItemsFilter(request.GET, queryset=Item.objects.all())
	context = {
		'itemsFilter': itemsFilter,
	}
	return render(request, 'webshop/search.html', context)


@login_required()
def cart(request):
	cart, created = Cart.objects.get_or_create(owner=request.user, active=True)
	item_amount = 0
	total_price = cart.get_total
	for order in cart.items.all():
		item_amount += order.quantity
	context = {
		'cart': cart,
		'item_amount': item_amount,
		'total_price': total_price,
	}
	return render(request, 'webshop/cart.html', context)


@login_required()
def add_item_to_cart(request, item_pk):
	item = get_object_or_404(Item, pk=item_pk)
	cart, created = Cart.objects.get_or_create(owner=request.user, active=True)
	try:
		cart.add_item(item)
	except OutOfStockError:
		messages.add_message(request, messages.ERROR, 'The stock of this item can\'t support your desired order')
	return redirect('cart')\

@login_required()
def update_item_in_cart(request, item_pk, amount):
	item = get_object_or_404(Item, pk=item_pk)
	cart, created = Cart.objects.get_or_create(owner=request.user, active=True)
	try:
		cart.update_item(item, amount)
	except OutOfStockError:
		messages.add_message(request, messages.ERROR, 'The stock of this item can\'t support your desired order')
	return redirect('cart')\

@login_required()
def remove_item_from_cart(request, item_pk):
	item = get_object_or_404(Item, pk=item_pk)
	cart = get_object_or_404(Cart, owner=request.user, active=True)
	cart.remove_item(item)
	return redirect('cart')


@login_required()
def delete_item_from_cart(request, item_pk):
	item = get_object_or_404(Item, pk=item_pk)
	cart = Cart.objects.get(owner=request.user, active=True)
	cart.delete_item(item)
	return redirect('cart')


@login_required
def buy_cart(request, email):
	cart = get_object_or_404(Cart, owner=request.user, active=True)
	if(cart.get_total() <= 0):
		return redirect('cart')
	cart.update_stock()
	context = {
		'total': cart.get_total(),
		'cart': cart,
		'user': request.user
	}
	send_confirmation_email(email, context)
	cart.active = False
	cart.save()
	return render(request, 'webshop/reciept.html', context)


class ItemsFilter(django_filters.FilterSet):
	name = django_filters.CharFilter(lookup_expr="icontains")
	price = django_filters.RangeFilter()
	brand = django_filters.ModelChoiceFilter(queryset=Brand.objects.all())
	tag = django_filters.ModelMultipleChoiceFilter(widget=forms.CheckboxSelectMultiple, queryset=Tag.objects.all())

webshop/templates/webshop/cart.html
{% extends "base.html" %}

{% load static %}
{% load mathfilters %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'webshop/css/cart.css' %}">
{% endblock %}

{% block js %}
<script type="text/javascript">
// Allows the user to press the enter key when changing the quantity
function handle_input(event, item_pk, quantity) {
  if (event.key === "Enter") {
    updateQuantity(item_pk, quantity);
  }
}

function subtractQuantity(item_pk) {
  let quantity = parseInt(document.getElementsByName(item_pk+"-quantity")[0].value) - 1;
  console.log(quantity);
  updateQuantity(item_pk, quantity);
}

function addQuantity(item_pk) {
  let quantity = parseInt(document.getElementsByName(item_pk+"-quantity")[0].value) + 1;
  console.log(quantity);
  updateQuantity(item_pk, quantity);
}

function updateQuantity(item_pk, quantity) {
  let location = "{% url 'update_item_in_cart_base' %}" + item_pk + "/" + quantity + "/";
  window.location.href = location;
}

function buyCart () {
    let email = document.getElementById('InputEmail1');
    if (validateEmail(email.value)) {
        window.location.href = "{% url 'buy_cart_base' %}" + email.value + '/';
    }
    else {
        email.classList.toggle('is-invalid');
        document.getElementById('emailHelp').innerHTML = 'Please provide a valid email address';
        document.getElementById('emailHelp').classList.add('invalid-help-text');
    }
}

function validateEmail(email) {
    const re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(email);
}

</script>
{% endblock %}

{% block content %}
<div class="cart">
  <div class="cart_item">
    <span>Shopping cart</span>
    <span>Quantity</span>
    <span>Stock</span>
    <span>Price</span>
    <span>Total</span>
    <span>Delete</span>
  </div>
  <div class="horizontal_line"></div>
  {% if item_amount == 0 %}
  <div class="cart_item">
    <span>There are no items in your cart.</span>
  </div>
  {% else %}
  {% for order in cart.items.all %}
  <div class="cart_item">
    <span>
      <a href="{% url 'detail' order.item.pk %}">{{ order.item.name }}</a>
      {% if order.item.get_discount %}[{{order.item.get_discount}}]{% endif %}
    </span>
    <div class="item_quantity_selector">
      <button class="btn_quantity_selector" onclick="subtractQuantity({{order.item.pk}})">-</button>
      <input class="input_quantity_selector" type="number" maxlength="3" min="1" name="{{order.item.pk}}-quantity" value={{order.quantity}} onkeydown="handle_input(event, {{order.item.pk}}, this.value)">
      <button class="btn_quantity_selector" onclick="addQuantity({{order.item.pk}})">+</button>
    </div>
    <span>{{order.item.stock}}</span>
    {% if order.item.get_item_percentage_price %}
      <span><span class="strikethrough">{{order.item.price}}</span> {{order.item.get_item_percentage_price}} NOK</span>
    {% else %}
      <span>{{order.item.price}} NOK</span>
    {% endif %}
    <span>{{order.get_order_total}} NOK</span>
    <a href="{% url 'delete_item_from_cart' order.item.pk %}">[X]</a>
  </div>
  <div class="horizontal_line"></div>
  {% endfor %}
      <h4>Subtotal ({{ item_amount }} items): {{ total_price }} NOK </h4>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
          Buy cart
      </button>
  {% endif %}

</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">

            <label for="InputEmail1">Please specify email adress to send reciept</label>
            <input type="email" class="form-control" id="InputEmail1" aria-describedby="emailHelp"
                placeholder="Enter email" required data-error-msg="The email is required in valid format!">
            <small id="emailHelp" class="form-text">We'll never share your email with anyone else.</small>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Abort</button>
        <button type="submit" class="btn btn-primary" onclick="buyCart()">Send reciept</button>
      </div>
    </div>
  </div>
</div>


{% endblock %}

webshop/templates/webshop/reciept.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'webshop/css/search.css' %}">
{% endblock %}

{% block content %}
    <div class="content">
    <h2>You bought stuff for {{ total }}NOK</h2>

    <div>What was bought
        {% for foo in cart.items.all %}
            <div>{{ foo.item.name }}</div>
            <div>{{ foo.quantity }}</div>
    {% endfor %}
    </div>
    </div>
{% endblock %}

webshop/templates/webshop/search.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'webshop/css/search.css' %}">
{% endblock %}

{% block content %}
<form id="filterForm" action="" method="get">
	<label for="id_name">Product Name</label> {{ itemsFilter.form.name }}
	<label for="id_price_0">Price</label> <div id="priceDiv">{{ itemsFilter.form.price }}</div>
	<label for="id_brand">Brand</label> {{ itemsFilter.form.brand }}
	<label>Tag</label> {{ itemsFilter.form.tag }}
	<input type=submit value="Filter">
</form>
<div class="items">
{% if itemsFilter.qs %}
	{% for item in itemsFilter.qs %}
	<div class="item">
		<a class="item_name" href="/webshop/{{ item.id }}/">{{item.name | truncatechars:14 }}</a>
		{% if item.get_discount %}
			{% if item.get_item_percentage_price %}
				<p class="item_price"><span class=strikethrough>{{item.price}}</span> {{item.get_item_percentage_price}} NOK ({{item.get_discount}})</p>
			{% else %}
				<p class="item_price">{{item.price}} NOK [{{item.get_discount}}]</p>
			{% endif %}
		{% else %}
			<p class="item_price">{{item.price}} NOK</p>
		{% endif %}
		<p class="item_brand">{{item.brand}} Brand</p>
		<p class="item_tags">
			{% for tag in item.tag.all %}
			<span>{{tag.name}}{% if not forloop.last %} | {% endif %}</span>
			{% endfor %}
		</p>
		{% if user.is_authenticated %}
            <a class="item_add_to_cart" href="{% url 'add_item_to_cart' item.pk %}">[Add To Cart]</a>
        {% endif %}
	</div>
	{% endfor %}
{% else %}
	<p>
		There are no items.
	</p>
{% endif %}
</div>
{% endblock %}